/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgForm;

import javax.swing.JOptionPane;

/**
 *
 * @author Jose Restrepo G
 */
public class frmEquipo extends javax.swing.JFrame {

    /**
     * Creates new form frmEquipo
     */
    public frmEquipo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barE = new javax.swing.JToolBar();
        btnAgregarE = new javax.swing.JButton();
        btnModificarE = new javax.swing.JButton();
        btnEliminarE = new javax.swing.JButton();
        btnConsultarE = new javax.swing.JButton();
        btnLimpiarE = new javax.swing.JButton();
        btnCerrarE = new javax.swing.JButton();
        lblCedulaE = new javax.swing.JLabel();
        txtCedulaE = new javax.swing.JTextField();
        lblNombreE = new javax.swing.JLabel();
        txtNombreE = new javax.swing.JTextField();
        lblEdadE = new javax.swing.JLabel();
        txtEdadE = new javax.swing.JTextField();
        lblPosicionE = new javax.swing.JLabel();
        txtPosicionE = new javax.swing.JTextField();
        lblEquipoE = new javax.swing.JLabel();
        txtEquipoE = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        barE.setRollover(true);

        btnAgregarE.setText("Agregar");
        btnAgregarE.setFocusable(false);
        btnAgregarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEActionPerformed(evt);
            }
        });
        barE.add(btnAgregarE);

        btnModificarE.setText("Modificar");
        btnModificarE.setFocusable(false);
        btnModificarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnModificarE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModificarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarEActionPerformed(evt);
            }
        });
        barE.add(btnModificarE);

        btnEliminarE.setText("Eliminar");
        btnEliminarE.setFocusable(false);
        btnEliminarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEliminarE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEliminarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEActionPerformed(evt);
            }
        });
        barE.add(btnEliminarE);

        btnConsultarE.setText("Consultar");
        btnConsultarE.setFocusable(false);
        btnConsultarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConsultarE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnConsultarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarEActionPerformed(evt);
            }
        });
        barE.add(btnConsultarE);

        btnLimpiarE.setText("Limpiar");
        btnLimpiarE.setFocusable(false);
        btnLimpiarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLimpiarE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLimpiarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEActionPerformed(evt);
            }
        });
        barE.add(btnLimpiarE);

        btnCerrarE.setText("Cerrar");
        btnCerrarE.setFocusable(false);
        btnCerrarE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCerrarE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCerrarE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarEActionPerformed(evt);
            }
        });
        barE.add(btnCerrarE);

        lblCedulaE.setText("Cédula.");

        lblNombreE.setText("Nombre.");

        lblEdadE.setText("Edad.");

        lblPosicionE.setText("Posición.");

        lblEquipoE.setText("Equipo.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(barE, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreE, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCedulaE, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtEdadE)
                    .addComponent(txtPosicionE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCedulaE)
                            .addComponent(lblNombreE)
                            .addComponent(lblEdadE)
                            .addComponent(lblPosicionE)
                            .addComponent(lblEquipoE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtEquipoE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCedulaE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCedulaE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombreE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEdadE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEdadE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPosicionE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPosicionE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEquipoE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEquipoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEActionPerformed
        // TODO add your handling code here:
        pkgClass.clsDAOEquipo obj;
        obj = new pkgClass.clsDAOEquipo();
        obj.setCedula(txtCedulaE.getText());
        obj.setNombrej(txtNombreE.getText());
        obj.setEdad(txtEdadE.getText());
        obj.setPosicion(txtPosicionE.getText());
        obj.setEquipo(txtEquipoE.getText());

        if(obj.getCedula().equals("") || obj.getNombrej().equals("") || obj.getEdad().equals("") || obj.getPosicion().equals("")  || obj.getEquipo().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No hay información en todos los campos.");
        }else{
            if (obj.insertar() == false){
                JOptionPane.showMessageDialog(rootPane, "Se insertó.");                
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se insertó.");
            }
        }
        txtCedulaE.setText("");
        txtNombreE.setText("");
        txtEdadE.setText("");
        txtPosicionE.setText("");
        txtEquipoE.setText("");
    }//GEN-LAST:event_btnAgregarEActionPerformed

    private void btnModificarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarEActionPerformed
        // TODO add your handling code here:
        pkgClass.clsDAOEquipo obj;
        obj = new pkgClass.clsDAOEquipo();
        obj.setCedula(txtCedulaE.getText());
        obj.setNombrej(txtNombreE.getText());
        obj.setEdad(txtEdadE.getText());
        obj.setPosicion(txtPosicionE.getText());
        obj.setEquipo(txtEquipoE.getText());
        
        if(obj.getCedula().equals("") || obj.getNombrej().equals("") || obj.getEdad().equals("") || obj.getPosicion().equals("")  || obj.getEquipo().equals("")){
            JOptionPane.showMessageDialog(rootPane, "No hay información en todos los campos.");
        }else{
            if(obj.modificar() == false){
                JOptionPane.showMessageDialog(rootPane, "No se modificó.");
            }else{                
                JOptionPane.showMessageDialog(rootPane, "Se modificó.");
            }
        }
        txtCedulaE.setText("");
        txtNombreE.setText("");
        txtEdadE.setText("");
        txtPosicionE.setText("");
        txtEquipoE.setText("");
    }//GEN-LAST:event_btnModificarEActionPerformed

    private void btnEliminarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEActionPerformed
        // TODO add your handling code here:
        pkgClass.clsDAOEquipo obj;
        obj = new pkgClass.clsDAOEquipo();
        obj.setCedula(txtCedulaE.getText());
        
        if(obj.getCedula().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Ingrese la cédula del jugador que desea eliminar.");
        }else{
            obj.borrar();
            if(obj.borrar() == false){
                JOptionPane.showMessageDialog(rootPane, "Se eliminó.");
            }else{
                JOptionPane.showMessageDialog(rootPane, "No se eliminó.");
            }
        }
        txtCedulaE.setText("");
        txtNombreE.setText("");
        txtEdadE.setText("");
        txtPosicionE.setText("");
        txtEquipoE.setText("");
    }//GEN-LAST:event_btnEliminarEActionPerformed

    private void btnConsultarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarEActionPerformed
        // TODO add your handling code here:
        pkgClass.clsDAOEquipo obj;
        obj = new pkgClass.clsDAOEquipo();
        obj.setCedula(txtCedulaE.getText());        
        String resultado1 = obj.consultar1();        
        String resultado2 = obj.consultar2();        
        String resultado3 = obj.consultar3();        
        String resultado4 = obj.consultar4();
        if(obj.getCedula().equals("")){
           JOptionPane.showMessageDialog(rootPane, "Ingrese la cédula del jugador que desea consultar."); 
        }else{
            if(resultado1.equals("no")){
                JOptionPane.showMessageDialog(rootPane, "No está.");
                txtCedulaE.setText("");
                txtNombreE.setText("");
                txtEdadE.setText("");
                txtPosicionE.setText("");
                txtEquipoE.setText("");
            }else{
                txtNombreE.setText(resultado1);
                txtEdadE.setText(resultado2);
                txtPosicionE.setText(resultado3);
                txtEquipoE.setText(resultado4);
            }            
        }  
    }//GEN-LAST:event_btnConsultarEActionPerformed

    private void btnCerrarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarEActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarEActionPerformed

    private void btnLimpiarEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEActionPerformed
        // TODO add your handling code here:
        txtCedulaE.setText("");
        txtNombreE.setText("");
        txtEdadE.setText("");
        txtPosicionE.setText("");
        txtEquipoE.setText("");
    }//GEN-LAST:event_btnLimpiarEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar barE;
    private javax.swing.JButton btnAgregarE;
    private javax.swing.JButton btnCerrarE;
    private javax.swing.JButton btnConsultarE;
    private javax.swing.JButton btnEliminarE;
    private javax.swing.JButton btnLimpiarE;
    private javax.swing.JButton btnModificarE;
    private javax.swing.JLabel lblCedulaE;
    private javax.swing.JLabel lblEdadE;
    private javax.swing.JLabel lblEquipoE;
    private javax.swing.JLabel lblNombreE;
    private javax.swing.JLabel lblPosicionE;
    private javax.swing.JTextField txtCedulaE;
    private javax.swing.JTextField txtEdadE;
    private javax.swing.JTextField txtEquipoE;
    private javax.swing.JTextField txtNombreE;
    private javax.swing.JTextField txtPosicionE;
    // End of variables declaration//GEN-END:variables
}
